#!/bin/bash
# GENERATED by `python scripts/portfolio.py --emit-bash --group hypc` - edit scripts/portfolio.py, not this file.
#
# Submits every job of the group in priority order, with one assemble job per unit that runs after its GPU and CPU
# jobs (--dependency=afterany, so a partial unit still assembles). All jobs of an experiment share ONE run directory:
# they compute cells (--compute-only) and leave a provenance record in <run_dir>/shards/; the assemble job writes
# tidy.csv, tables and figures. The agent never submits: you run this ONCE on the login node. Jobs beyond the
# per-user caps (2 GPUs on `main`, 8 CPUs on `main-cpu`) wait in the queue. Watch with `squeue --me`.
set -euo pipefail
cd "${SLURM_SUBMIT_DIR:-$PWD}"

# submit_unit <name> <experiment> <script> <config> <env> <gpu-models|-> <cpu-models|-> <lanes> <mem|-> [overrides...]
submit_unit() {
  local name="$1" exp="$2" script="$3" cfg="$4" env="$5" gpu="$6" cpu="$7" lanes="$8" mem="$9" deps="" id
  shift 9
  local extra=("$@") memflag=()
  if [ "$mem" != "-" ]; then memflag=(--mem="$mem"); fi
  if [ "$gpu" != "-" ]; then
    id=$(CONDA_ENV="$env" LANES="$lanes" sbatch --parsable ${memflag[@]+"${memflag[@]}"} "$script" "$cfg" "models=[$gpu]" ${extra[@]+"${extra[@]}"})
    deps="$deps:${id%%;*}"
  fi
  if [ "$cpu" != "-" ]; then
    id=$(CONDA_ENV="$env" sbatch --parsable scripts/run_cpu.sh "$exp" "$cfg" "models=[$cpu]" ${extra[@]+"${extra[@]}"})
    deps="$deps:${id%%;*}"
  fi
  id=$(CONDA_ENV="$env" sbatch --parsable --dependency="afterany$deps" scripts/run_assemble.sh "$exp" "$cfg" ${extra[@]+"${extra[@]}"})
  echo "submitted: $name  (assemble job ${id%%;*} runs after$deps)"
}

# submit_single <name> <experiment> <config> <env> [overrides...]   (one process, writes its own outputs)
submit_single() {
  local name="$1" exp="$2" cfg="$3" env="$4" id
  shift 4
  id=$(CONDA_ENV="$env" sbatch --parsable scripts/run_single.sh "$exp" "$cfg" "$@")
  echo "submitted: $name  (job ${id%%;*})"
}

submit_single "C1. M10 update rule, NHP" mechanism configs/experiment/mechanism_update_rule_nhp.yaml pfns4neurostim
submit_single "C2. Placement (MMD / sliced W2), NHP" mechanism configs/experiment/mechanism_placement_nhp.yaml pfns4neurostim
submit_single "C3. CKA, NHP" mechanism configs/experiment/mechanism_cka_nhp.yaml pfns4neurostim

echo "Done. Check with: squeue --me"
