#!/bin/bash
# GENERATED by `python scripts/portfolio.py --emit-split mila` - edit SPLIT_PLAN in scripts/portfolio.py, not this file.
#
# Split deployment (2026-10-05): GPU halves on Mila, CPU halves and GPU overflow on Narval. These jobs only COMPUTE
# cells; there is no assemble job here -- the halves meet in the LOCAL cache and are assembled locally with
# --only-cached. Run one wave at a time and review its probe first:   bash <this script> probe|bulk|synthetic
# YOU run this on the Mila login node (the agent never submits on Mila). `main` allows 8 CPUs per user, so with
# 6-lane jobs exactly one GPU job runs at a time and the rest wait (QOSMaxCpuPerUserLimit) -- intended.
set -euo pipefail
cd "${SLURM_SUBMIT_DIR:-$PWD}"
read -r -a GPU_FLAGS <<< "$(bash scripts/cluster.sh flags gpu)"
read -r -a CPU_FLAGS <<< "$(bash scripts/cluster.sh flags cpu)"
wave="${1:?usage: bash $0 probe|bulk|synthetic}"
case "$wave" in
  probe)
    CONDA_ENV=pfns4neurostim LANES=6 sbatch --parsable ${GPU_FLAGS[@]} --cpus-per-task=6 --mem=10G --time=02:00:00 --job-name=N9-gpu scripts/run_bo_benchmark.sh configs/experiment/hyp0_acq_core_nhp.yaml "models=[tabpfn_v2_5]"
    CONDA_ENV=pfns4neurostim-bench LANES=1 sbatch --parsable ${GPU_FLAGS[@]} --cpus-per-task=1 --mem=24G --time=01:00:00 --job-name=E4-gpu scripts/run_bo_benchmark.sh configs/experiment/hyp0_pfn_bench_5d_rat.yaml "models=[tabfm]" "dataset.subjects=[1]" "dataset.emgs=[0]" "n_reps=2" "tag=5d_rat-tabfm-calibration"
    ;;
  bulk)
    CONDA_ENV=pfns4neurostim LANES=6 sbatch --parsable ${GPU_FLAGS[@]} --cpus-per-task=6 --mem=10G --time=05:15:00 --job-name=N2-gpu scripts/run_stress_sweep.sh configs/experiment/stress_k2_global_nhp.yaml "models=[tabpfn_v2_5]"
    CONDA_ENV=pfns4neurostim LANES=6 sbatch --parsable ${GPU_FLAGS[@]} --cpus-per-task=6 --mem=10G --time=04:00:00 --job-name=N3-gpu scripts/run_stress_sweep.sh configs/experiment/stress_k5_nhp.yaml "models=[tabpfn_v2_5]"
    CONDA_ENV=pfns4neurostim LANES=6 sbatch --parsable ${GPU_FLAGS[@]} --cpus-per-task=6 --mem=10G --time=03:15:00 --job-name=N4-gpu scripts/run_stress_sweep.sh configs/experiment/stress_k6_failure_nhp.yaml "models=[tabpfn_v2_5]"
    CONDA_ENV=pfns4neurostim LANES=6 sbatch --parsable ${GPU_FLAGS[@]} --cpus-per-task=6 --mem=10G --time=01:30:00 --job-name=N5-gpu scripts/run_stress_sweep.sh configs/experiment/stress_k6_budget_nhp.yaml "models=[tabpfn_v2_5]"
    CONDA_ENV=pfns4neurostim-bench LANES=6 sbatch --parsable ${GPU_FLAGS[@]} --cpus-per-task=6 --mem=12G --time=02:00:00 --job-name=N11-gpu scripts/run_bo_benchmark.sh configs/experiment/hyp0_pfn_bench_nhp.yaml "models=[tabicl]"
    CONDA_ENV=pfns4neurostim-bench LANES=6 sbatch --parsable ${GPU_FLAGS[@]} --cpus-per-task=6 --mem=12G --time=02:00:00 --job-name=E1-gpu scripts/run_bo_benchmark.sh configs/experiment/hyp0_pfn_bench_5d_rat.yaml "models=[tabicl]"
    ;;
  synthetic)
    CONDA_ENV=pfns4neurostim LANES=6 sbatch --parsable ${GPU_FLAGS[@]} --cpus-per-task=6 --mem=10G --time=03:15:00 --job-name=N7-gpu scripts/run_stress_sweep.sh configs/experiment/stress_k1_decoy_nhp.yaml "models=[tabpfn_v2_5]"
    CONDA_ENV=pfns4neurostim LANES=6 sbatch --parsable ${GPU_FLAGS[@]} --cpus-per-task=6 --mem=10G --time=05:45:00 --job-name=N6-gpu scripts/run_stress_sweep.sh configs/experiment/stress_k2_channel_synthetic_nhp.yaml "models=[tabpfn_v2_5]"
    ;;
  *) echo "unknown wave: $wave (probe|bulk|synthetic)" >&2; exit 2 ;;
esac
echo "estimates for mila: GPU ~24 job-h, CPU ~0 core-h (all waves)"
