#!/bin/bash
# GENERATED by `python scripts/portfolio.py --emit-split narval` - edit SPLIT_PLAN in scripts/portfolio.py, not this file.
#
# Split deployment (2026-10-05): GPU halves on Mila, CPU halves and GPU overflow on Narval. These jobs only COMPUTE
# cells; there is no assemble job here -- the halves meet in the LOCAL cache and are assembled locally with
# --only-cached. Run one wave at a time and review its probe first:   bash <this script> probe|bulk|synthetic
# The agent runs these lines one by one after your approval (each is a `narval.sh do sbatch` call, audited in
# output/logs/narval_audit.log). NARVAL_DRY_RUN=1 prints the remote commands without submitting.
set -euo pipefail
wave="${1:?usage: bash $0 probe|bulk|synthetic}"
case "$wave" in
  probe)
    echo "nothing in this wave for this cluster" ;;
  bulk)
    bash scripts/narval.sh do sbatch cpu --conda-env pfns4neurostim --cpus 18 --mem 27G --time 03:00:00 --job-name N2-cpu -- scripts/run_cpu.sh stress_sweep configs/experiment/stress_k2_global_nhp.yaml "models=[gp_mll,gp_naive]"
    bash scripts/narval.sh do sbatch cpu --conda-env pfns4neurostim --cpus 18 --mem 27G --time 02:15:00 --job-name N3-cpu -- scripts/run_cpu.sh stress_sweep configs/experiment/stress_k5_nhp.yaml "models=[gp_mll,gp_naive]"
    bash scripts/narval.sh do sbatch cpu --conda-env pfns4neurostim --cpus 18 --mem 27G --time 02:00:00 --job-name N4-cpu -- scripts/run_cpu.sh stress_sweep configs/experiment/stress_k6_failure_nhp.yaml "models=[gp_mll,gp_naive]"
    bash scripts/narval.sh do sbatch cpu --conda-env pfns4neurostim --cpus 18 --mem 27G --time 01:00:00 --job-name N5-cpu -- scripts/run_cpu.sh stress_sweep configs/experiment/stress_k6_budget_nhp.yaml "models=[gp_mll,gp_naive]"
    bash scripts/narval.sh do sbatch cpu --conda-env pfns4neurostim --cpus 18 --mem 27G --time 01:15:00 --job-name N9-cpu -- scripts/run_cpu.sh bo_benchmark configs/experiment/hyp0_acq_core_nhp.yaml "models=[gp_mll]"
    bash scripts/narval.sh do sbatch cpu --conda-env pfns4neurostim --cpus 17 --mem 26G --time 00:15:00 --job-name S2b-cpu -- scripts/run_cpu.sh stress_sweep configs/experiment/stress_k2_global_5d_rat.yaml "models=[gp_naive]"
    bash scripts/narval.sh do sbatch cpu --conda-env pfns4neurostim --cpus 17 --mem 26G --time 02:45:00 --job-name S3b-cpu -- scripts/run_cpu.sh stress_sweep configs/experiment/stress_k5_5d_rat.yaml "models=[gp_mll,gp_naive]"
    bash scripts/narval.sh do sbatch cpu --conda-env pfns4neurostim --cpus 17 --mem 26G --time 02:15:00 --job-name S4b-cpu -- scripts/run_cpu.sh stress_sweep configs/experiment/stress_k6_failure_5d_rat.yaml "models=[gp_mll,gp_naive]"
    bash scripts/narval.sh do sbatch gpu --lanes 4 --conda-env pfns4neurostim-latest --gpu-type a100_2g.10gb --cpus 4 --mem 20G --time 02:30:00 --job-name E9-gpu -- scripts/run_bo_benchmark.sh configs/experiment/hyp0_pfn_bench_nhp.yaml "models=[tabpfn_v3_5,causilo]"
    bash scripts/narval.sh do sbatch gpu --lanes 4 --conda-env pfns4neurostim-latest --gpu-type a100_2g.10gb --cpus 4 --mem 20G --time 02:30:00 --job-name E9-gpu-rat -- scripts/run_bo_benchmark.sh configs/experiment/hyp0_pfn_bench_5d_rat.yaml "models=[tabpfn_v3_5,causilo]"
    ;;
  synthetic)
    bash scripts/narval.sh do sbatch gpu --lanes 4 --conda-env pfns4neurostim --gpu-type a100_2g.10gb --cpus 4 --mem 8G --time 05:45:00 --job-name N7-gpu -- scripts/run_stress_sweep.sh configs/experiment/stress_k1_decoy_nhp.yaml "models=[tabpfn_v2_5]"
    bash scripts/narval.sh do sbatch gpu --lanes 4 --conda-env pfns4neurostim --gpu-type a100_2g.10gb --cpus 4 --mem 8G --time 04:30:00 --job-name N6-gpu-p0 -- scripts/run_stress_sweep.sh configs/experiment/stress_k2_channel_synthetic_nhp.yaml "models=[tabpfn_v2_5]" "dataset.subjects=[0]"
    bash scripts/narval.sh do sbatch gpu --lanes 4 --conda-env pfns4neurostim --gpu-type a100_2g.10gb --cpus 4 --mem 8G --time 04:30:00 --job-name N6-gpu-p1 -- scripts/run_stress_sweep.sh configs/experiment/stress_k2_channel_synthetic_nhp.yaml "models=[tabpfn_v2_5]" "dataset.subjects=[1]"
    bash scripts/narval.sh do sbatch gpu --lanes 4 --conda-env pfns4neurostim --gpu-type a100_2g.10gb --cpus 4 --mem 8G --time 04:30:00 --job-name N6-gpu-p2 -- scripts/run_stress_sweep.sh configs/experiment/stress_k2_channel_synthetic_nhp.yaml "models=[tabpfn_v2_5]" "dataset.subjects=[3]"
    bash scripts/narval.sh do sbatch cpu --conda-env pfns4neurostim --cpus 18 --mem 27G --time 02:00:00 --job-name N7-cpu -- scripts/run_cpu.sh stress_sweep configs/experiment/stress_k1_decoy_nhp.yaml "models=[gp_mll,gp_naive]"
    bash scripts/narval.sh do sbatch cpu --conda-env pfns4neurostim --cpus 18 --mem 27G --time 03:15:00 --job-name N6-cpu -- scripts/run_cpu.sh stress_sweep configs/experiment/stress_k2_channel_synthetic_nhp.yaml "models=[gp_mll]"
    bash scripts/narval.sh do sbatch cpu --conda-env pfns4neurostim --cpus 17 --mem 26G --time 04:00:00 --job-name S5b-cpu -- scripts/run_cpu.sh stress_sweep configs/experiment/stress_k2_channel_synthetic_5d_rat.yaml "models=[gp_mll,gp_naive]"
    bash scripts/narval.sh do sbatch gpu --lanes 4 --conda-env pfns4neurostim --gpu-type a100_2g.10gb --cpus 4 --mem 8G --time 08:15:00 --job-name S5b-gpu-p0 -- scripts/run_stress_sweep.sh configs/experiment/stress_k2_channel_synthetic_5d_rat.yaml "models=[tabpfn_v2_5]" "dataset.subjects=[0]"
    bash scripts/narval.sh do sbatch gpu --lanes 4 --conda-env pfns4neurostim --gpu-type a100_2g.10gb --cpus 4 --mem 8G --time 08:15:00 --job-name S5b-gpu-p1 -- scripts/run_stress_sweep.sh configs/experiment/stress_k2_channel_synthetic_5d_rat.yaml "models=[tabpfn_v2_5]" "dataset.subjects=[1]"
    bash scripts/narval.sh do sbatch gpu --lanes 4 --conda-env pfns4neurostim --gpu-type a100_2g.10gb --cpus 4 --mem 8G --time 08:15:00 --job-name S5b-gpu-p2 -- scripts/run_stress_sweep.sh configs/experiment/stress_k2_channel_synthetic_5d_rat.yaml "models=[tabpfn_v2_5]" "dataset.subjects=[2]"
    bash scripts/narval.sh do sbatch gpu --lanes 4 --conda-env pfns4neurostim --gpu-type a100_2g.10gb --cpus 4 --mem 8G --time 08:15:00 --job-name S5b-gpu-p3 -- scripts/run_stress_sweep.sh configs/experiment/stress_k2_channel_synthetic_5d_rat.yaml "models=[tabpfn_v2_5]" "dataset.subjects=[3]"
    bash scripts/narval.sh do sbatch gpu --lanes 4 --conda-env pfns4neurostim --gpu-type a100_2g.10gb --cpus 4 --mem 8G --time 08:15:00 --job-name S5b-gpu-p4 -- scripts/run_stress_sweep.sh configs/experiment/stress_k2_channel_synthetic_5d_rat.yaml "models=[tabpfn_v2_5]" "dataset.subjects=[4]"
    ;;
  *) echo "unknown wave: $wave (probe|bulk|synthetic)" >&2; exit 2 ;;
esac
echo "estimates for narval: GPU ~52 job-h, CPU ~364 core-h (all waves)"
