#!/bin/bash
# GENERATED by `python scripts/portfolio.py --emit-bash --group hypc` - edit scripts/portfolio.py, not this file.
#
# Submits every job of the group in priority order, with one assemble job per unit that runs after its GPU and CPU
# jobs (--dependency=afterany, so a partial unit still assembles). All jobs of an experiment share ONE run directory:
# they compute cells (--compute-only) and leave a provenance record in <run_dir>/shards/; the assemble job writes
# tidy.csv, tables and figures. The agent never submits: you run this ONCE on the login node. Jobs beyond the
# per-user caps (on Mila: 2 GPUs on `main`, 8 CPUs on `main-cpu`) wait in the queue. Watch with `squeue --me`.
# Runs unchanged on Mila and Narval: the cluster-specific sbatch flags come from scripts/cluster.sh.
set -euo pipefail
cd "${SLURM_SUBMIT_DIR:-$PWD}"
read -r -a GPU_FLAGS <<< "$(bash scripts/cluster.sh flags gpu)"
read -r -a CPU_FLAGS <<< "$(bash scripts/cluster.sh flags cpu)"

# submit_unit <name> <experiment> <script> <config> <env> <gpu-models|-> <cpu-models|-> <lanes> <mem|-> <parts|-> [overrides...]
#   parts: '|'-separated compute-only overrides, one GPU job each; the assemble job never sees a part (full grid).
submit_unit() {
  local name="$1" exp="$2" script="$3" cfg="$4" env="$5" gpu="$6" cpu="$7" lanes="$8" mem="$9" parts="${10}" deps="" id part
  shift 10
  local extra=("$@") memflag=() plist=()
  if [ "$mem" != "-" ]; then memflag=(--mem="$mem"); fi
  if [ "$parts" = "-" ]; then plist=(""); else IFS="|" read -r -a plist <<< "$parts"; fi
  if [ "$gpu" != "-" ]; then
    for part in "${plist[@]}"; do
      id=$(CONDA_ENV="$env" LANES="$lanes" sbatch --parsable ${GPU_FLAGS[@]+"${GPU_FLAGS[@]}"} ${memflag[@]+"${memflag[@]}"} "$script" "$cfg" "models=[$gpu]" ${part:+"$part"} ${extra[@]+"${extra[@]}"})
      deps="$deps:${id%%;*}"
    done
  fi
  if [ "$cpu" != "-" ]; then
    id=$(CONDA_ENV="$env" sbatch --parsable ${CPU_FLAGS[@]+"${CPU_FLAGS[@]}"} scripts/run_cpu.sh "$exp" "$cfg" "models=[$cpu]" ${extra[@]+"${extra[@]}"})
    deps="$deps:${id%%;*}"
  fi
  id=$(CONDA_ENV="$env" sbatch --parsable ${CPU_FLAGS[@]+"${CPU_FLAGS[@]}"} --dependency="afterany$deps" scripts/run_assemble.sh "$exp" "$cfg" ${extra[@]+"${extra[@]}"})
  echo "submitted: $name  (assemble job ${id%%;*} runs after$deps)"
}

# submit_single <name> <experiment> <config> <env> <script> [overrides...]   (one process, writes its own outputs)
submit_single() {
  local name="$1" exp="$2" cfg="$3" env="$4" script="$5" id flags=(${GPU_FLAGS[@]+"${GPU_FLAGS[@]}"})
  shift 5
  case "$script" in *_cpu.sh) flags=(${CPU_FLAGS[@]+"${CPU_FLAGS[@]}"}) ;; esac
  id=$(CONDA_ENV="$env" sbatch --parsable ${flags[@]+"${flags[@]}"} "$script" "$exp" "$cfg" "$@")
  echo "submitted: $name  (job ${id%%;*})"
}

submit_single "C1. M10 update rule (t = 10/25/50), NHP" mechanism configs/experiment/mechanism_update_rule_nhp.yaml pfns4neurostim scripts/run_single.sh
submit_single "C2. CKA (a) + placement ladder (t = 10/25/50/80), NHP" mechanism configs/experiment/mechanism_cka_nhp.yaml pfns4neurostim scripts/run_single.sh
submit_single "C3. Placement MMD / W2 (t = 10...96), NHP" mechanism configs/experiment/mechanism_placement_nhp.yaml pfns4neurostim scripts/run_single_cpu.sh
submit_single "C4. Placement MMD / W2 (t = 10...200), 5d_rat" mechanism configs/experiment/mechanism_placement_5d_rat.yaml pfns4neurostim scripts/run_single_cpu.sh

echo "Done. Check with: squeue --me"
