#!/bin/bash
# GENERATED by `python scripts/portfolio.py --emit-bash` - edit scripts/portfolio.py, not this file.
#
# Submits every cluster job in priority order, with one auto-assemble job per unit that runs after its GPU
# and CPU jobs finish (--dependency=afterany, so a partial unit still assembles). Run it ONCE on the login
# node; jobs then run unattended (requeue on preemption, cached cells resume), so you can go to sleep.
# The agent never submits: you run this. Jobs beyond the per-user caps (2 GPUs on `main`, 8 CPUs on
# `main-cpu`) simply wait in the queue. Watch with `squeue --me`.
set -euo pipefail
cd "${SLURM_SUBMIT_DIR:-$PWD}"

# submit_unit <name> <experiment> <script> <config> <env> <gpu-models|-> <cpu-models|->
submit_unit() {
  local name="$1" exp="$2" script="$3" cfg="$4" env="$5" gpu="$6" cpu="$7" deps="" id
  if [ "$gpu" != "-" ]; then
    id=$(CONDA_ENV="$env" LANES=4 sbatch --parsable "$script" "$cfg" "models=[$gpu]" tag=gpu)
    deps="$deps:${id%%;*}"
  fi
  if [ "$cpu" != "-" ]; then
    id=$(CONDA_ENV="$env" sbatch --parsable scripts/run_cpu.sh "$exp" "$cfg" "models=[$cpu]" tag=cpu)
    deps="$deps:${id%%;*}"
  fi
  id=$(CONDA_ENV="$env" sbatch --parsable --dependency="afterany$deps" scripts/run_assemble.sh "$exp" "$cfg")
  echo "submitted: $name  (assemble job ${id%%;*} runs after$deps)"
}

submit_unit "1. D1 5d_rat" bo_benchmark scripts/run_bo_benchmark.sh configs/experiment/hyp_a_5d_rat.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive,random"
submit_unit "2a. K2 noise amplification NHP" stress_sweep scripts/run_stress_sweep.sh configs/experiment/stress_k2_nhp.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive"
submit_unit "2b. K2 noise amplification 5d_rat" stress_sweep scripts/run_stress_sweep.sh configs/experiment/stress_k2_5d_rat.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive"
submit_unit "3a. D3 PFN benchmark NHP (TabPFN-2.5, TabICL, GP-MLL)" bo_benchmark scripts/run_bo_benchmark.sh configs/experiment/hyp0_pfn_bench_nhp.yaml pfns4neurostim-bench "tabpfn_v2_5,tabicl" "gp_mll"
submit_unit "3b. D3 PFN benchmark 5d_rat (TabPFN-2.5, TabICL, GP-MLL)" bo_benchmark scripts/run_bo_benchmark.sh configs/experiment/hyp0_pfn_bench_5d_rat.yaml pfns4neurostim-bench "tabpfn_v2_5,tabicl" "gp_mll"
submit_unit "4. K5 outliers 5d_rat" stress_sweep scripts/run_stress_sweep.sh configs/experiment/stress_k5_5d_rat.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive"
submit_unit "5a. D3 TabFM NHP (LAST PFN job)" bo_benchmark scripts/run_bo_benchmark.sh configs/experiment/hyp0_pfn_bench_nhp.yaml pfns4neurostim-bench "tabfm" "-"
submit_unit "5b. D3 TabFM 5d_rat (LAST PFN job)" bo_benchmark scripts/run_bo_benchmark.sh configs/experiment/hyp0_pfn_bench_5d_rat.yaml pfns4neurostim-bench "tabfm" "-"

echo "Done. Check with: squeue --me"
