#!/bin/bash
# GENERATED by `python scripts/portfolio.py --emit-bash --group externals` - edit scripts/portfolio.py, not this file.
#
# Submits every job of the group in priority order, with one assemble job per unit that runs after its GPU and CPU
# jobs (--dependency=afterany, so a partial unit still assembles). All jobs of an experiment share ONE run directory:
# they compute cells (--compute-only) and leave a provenance record in <run_dir>/shards/; the assemble job writes
# tidy.csv, tables and figures. The agent never submits: you run this ONCE on the login node. Jobs beyond the
# per-user caps (2 GPUs on `main`, 8 CPUs on `main-cpu`) wait in the queue. Watch with `squeue --me`.
set -euo pipefail
cd "${SLURM_SUBMIT_DIR:-$PWD}"

# submit_unit <name> <experiment> <script> <config> <env> <gpu-models|-> <cpu-models|-> <lanes> <mem|-> [overrides...]
submit_unit() {
  local name="$1" exp="$2" script="$3" cfg="$4" env="$5" gpu="$6" cpu="$7" lanes="$8" mem="$9" deps="" id
  shift 9
  local extra=("$@") memflag=()
  if [ "$mem" != "-" ]; then memflag=(--mem="$mem"); fi
  if [ "$gpu" != "-" ]; then
    id=$(CONDA_ENV="$env" LANES="$lanes" sbatch --parsable ${memflag[@]+"${memflag[@]}"} "$script" "$cfg" "models=[$gpu]" ${extra[@]+"${extra[@]}"})
    deps="$deps:${id%%;*}"
  fi
  if [ "$cpu" != "-" ]; then
    id=$(CONDA_ENV="$env" sbatch --parsable scripts/run_cpu.sh "$exp" "$cfg" "models=[$cpu]" ${extra[@]+"${extra[@]}"})
    deps="$deps:${id%%;*}"
  fi
  id=$(CONDA_ENV="$env" sbatch --parsable --dependency="afterany$deps" scripts/run_assemble.sh "$exp" "$cfg" ${extra[@]+"${extra[@]}"})
  echo "submitted: $name  (assemble job ${id%%;*} runs after$deps)"
}

# submit_single <name> <experiment> <config> <env> [overrides...]   (one process, writes its own outputs)
submit_single() {
  local name="$1" exp="$2" cfg="$3" env="$4" id
  shift 4
  id=$(CONDA_ENV="$env" sbatch --parsable scripts/run_single.sh "$exp" "$cfg" "$@")
  echo "submitted: $name  (job ${id%%;*})"
}

submit_unit "E1. PFN bench base (TabPFN-2.5, TabICL / GP-MLL), 5d_rat" bo_benchmark scripts/run_bo_benchmark.sh configs/experiment/hyp0_pfn_bench_5d_rat.yaml pfns4neurostim-bench "tabpfn_v2_5,tabicl" "gp_mll" 4 "-"
submit_unit "E3. TabFM, NHP (fixed wrapper)" bo_benchmark scripts/run_bo_benchmark.sh configs/experiment/hyp0_pfn_bench_nhp.yaml pfns4neurostim-bench "tabfm" "-" 2 "24G"
submit_unit "E4. TabFM 5d_rat CALIBRATION (1 channel, 2 reps)" bo_benchmark scripts/run_bo_benchmark.sh configs/experiment/hyp0_pfn_bench_5d_rat.yaml pfns4neurostim-bench "tabfm" "-" 1 "24G" "dataset.subjects=[1]" "dataset.emgs=[0]" "n_reps=2" "tag=5d_rat-tabfm-calibration"
submit_unit "E6. PFNs4BO (native policy), 5d_rat" bo_benchmark scripts/run_bo_benchmark.sh configs/experiment/hyp0_pfn_bench_5d_rat.yaml pfns4neurostim "pfns4bo" "-" 2 "-"
submit_unit "E7. TabPFN v1 (classification-head adaptation), NHP" bo_benchmark scripts/run_bo_benchmark.sh configs/experiment/hyp0_pfn_bench_nhp.yaml pfns4neurostim-v1 "tabpfn_v1" "-" 2 "-"
submit_unit "E8. TabPFN v1 (classification-head adaptation), 5d_rat" bo_benchmark scripts/run_bo_benchmark.sh configs/experiment/hyp0_pfn_bench_5d_rat.yaml pfns4neurostim-v1 "tabpfn_v1" "-" 2 "-"

echo "Done. Check with: squeue --me"
