#!/bin/bash
# GENERATED by `python scripts/portfolio.py --emit-bash --group stress` - edit scripts/portfolio.py, not this file.
#
# Submits every job of the group in priority order, with one assemble job per unit that runs after its GPU and CPU
# jobs (--dependency=afterany, so a partial unit still assembles). All jobs of an experiment share ONE run directory:
# they compute cells (--compute-only) and leave a provenance record in <run_dir>/shards/; the assemble job writes
# tidy.csv, tables and figures. The agent never submits: you run this ONCE on the login node. Jobs beyond the
# per-user caps (2 GPUs on `main`, 8 CPUs on `main-cpu`) wait in the queue. Watch with `squeue --me`.
set -euo pipefail
cd "${SLURM_SUBMIT_DIR:-$PWD}"

# submit_unit <name> <experiment> <script> <config> <env> <gpu-models|-> <cpu-models|-> <lanes> <mem|-> [overrides...]
submit_unit() {
  local name="$1" exp="$2" script="$3" cfg="$4" env="$5" gpu="$6" cpu="$7" lanes="$8" mem="$9" deps="" id
  shift 9
  local extra=("$@") memflag=()
  if [ "$mem" != "-" ]; then memflag=(--mem="$mem"); fi
  if [ "$gpu" != "-" ]; then
    id=$(CONDA_ENV="$env" LANES="$lanes" sbatch --parsable ${memflag[@]+"${memflag[@]}"} "$script" "$cfg" "models=[$gpu]" ${extra[@]+"${extra[@]}"})
    deps="$deps:${id%%;*}"
  fi
  if [ "$cpu" != "-" ]; then
    id=$(CONDA_ENV="$env" sbatch --parsable scripts/run_cpu.sh "$exp" "$cfg" "models=[$cpu]" ${extra[@]+"${extra[@]}"})
    deps="$deps:${id%%;*}"
  fi
  id=$(CONDA_ENV="$env" sbatch --parsable --dependency="afterany$deps" scripts/run_assemble.sh "$exp" "$cfg" ${extra[@]+"${extra[@]}"})
  echo "submitted: $name  (assemble job ${id%%;*} runs after$deps)"
}

# submit_single <name> <experiment> <config> <env> [overrides...]   (one process, writes its own outputs)
submit_single() {
  local name="$1" exp="$2" cfg="$3" env="$4" id
  shift 4
  id=$(CONDA_ENV="$env" sbatch --parsable scripts/run_single.sh "$exp" "$cfg" "$@")
  echo "submitted: $name  (job ${id%%;*})"
}

# The K2-channel units reuse the pre-restructure k2_snr cells: relabel them first (idempotent, copies only).
# The login node has no python on PATH: load conda and run inside the main env (the script imports the package).
if ! command -v conda >/dev/null 2>&1; then set +u; module load anaconda/3; set -u; fi
conda run -n pfns4neurostim python scripts/relabel_knob_cells.py --apply

submit_unit "S1a. K2-channel, NHP (alpha = 8 top-up)" stress_sweep scripts/run_stress_sweep.sh configs/experiment/stress_k2_channel_nhp.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive" 4 "-"
submit_unit "S1b. K2-channel, 5d_rat (alpha = 8 top-up)" stress_sweep scripts/run_stress_sweep.sh configs/experiment/stress_k2_channel_5d_rat.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive" 4 "-"
submit_unit "S2a. K2-global, NHP" stress_sweep scripts/run_stress_sweep.sh configs/experiment/stress_k2_global_nhp.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive" 4 "-"
submit_unit "S2b. K2-global, 5d_rat" stress_sweep scripts/run_stress_sweep.sh configs/experiment/stress_k2_global_5d_rat.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive" 4 "-"
submit_unit "S3a. K5 slot-fraction heavy tail, NHP" stress_sweep scripts/run_stress_sweep.sh configs/experiment/stress_k5_nhp.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive" 4 "-"
submit_unit "S3b. K5 slot-fraction heavy tail, 5d_rat" stress_sweep scripts/run_stress_sweep.sh configs/experiment/stress_k5_5d_rat.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive" 4 "-"
submit_unit "S4a. K6 electrode failure, NHP" stress_sweep scripts/run_stress_sweep.sh configs/experiment/stress_k6_failure_nhp.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive" 4 "-"
submit_unit "S4b. K6 electrode failure, 5d_rat" stress_sweep scripts/run_stress_sweep.sh configs/experiment/stress_k6_failure_5d_rat.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive" 4 "-"
submit_unit "S4c. K6 budget, NHP" stress_sweep scripts/run_stress_sweep.sh configs/experiment/stress_k6_budget_nhp.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive" 4 "-"
submit_unit "S5a. Demo 1 K2-channel, NHP twins" stress_sweep scripts/run_stress_sweep.sh configs/experiment/stress_k2_channel_demo1_nhp.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive" 4 "-"
submit_unit "S5b. Demo 1 K2-channel, 5d_rat twins" stress_sweep scripts/run_stress_sweep.sh configs/experiment/stress_k2_channel_demo1_5d_rat.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive" 4 "-"
submit_unit "S5c. Demo 1 K1 decoy, NHP twins" stress_sweep scripts/run_stress_sweep.sh configs/experiment/stress_k1_decoy_nhp.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive" 4 "-"
submit_unit "S6. Split-half GT, K2-channel NHP" stress_sweep scripts/run_stress_sweep.sh configs/experiment/stress_k2_channel_nhp.yaml pfns4neurostim "tabpfn_v2_5" "gp_mll,gp_naive" 4 "-" "gt_mode=split_half" "tag=nhp-sh"

echo "Done. Check with: squeue --me"
